// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }


import Navbar from './components/navbar'
import Footer from './components/footer'
import Image from 'next/image';
import './globals.css'
import type { ReactNode } from 'react';

export const metadata = {
	title: 'Devaanshi Chaturvedi | Portfolio',
	description: 'This is my portfolio. Welcome to my world!',
  keywords: ["developer", "portfolio", "MERN developer", "Next.js developer", "Linux Enthusiast", "Full stack developer", "programmer", "vercel"]
}

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {

	return (
		<html lang="en">
			<body>
				<div className="parent">
					<div className="top_left_image">
						<Image
							src="/home/top-left.webp"
							alt="top-left"
							width={400}
							height={400}
						/>
					</div>
					<div className="bottom_right_image">
						<Image
							src="/home/bulb.webp"
							alt="bottom-right"
							width={256}
							height={392}
						/>
					</div>

					<Navbar />
					{children}
					<Footer />
				</div>
			</body>
		</html>
	)
}
